const UserInfo = {
  name: "曹凯",
  phone: "13390945900",
  email: "2655257336@qq.com",
  photo: "https://q1.qlogo.cn/g?b=qq&nk=2655257336&s=640",
  age: 20,
  gender: "男",
  experience: "1",
  status: "在读",
  job: "前端开发工程师",
  about: [
    "热爱编程，有良好的编码习惯，注重代码的可读性与维护性",
    "具有良好的抗压能力，沟通能力，团队合作能力",
    "擅长独立思考问题，学习能力较为良好，喜欢接触了解并学习新事物新技术",
  ],
  education: {
    school: "苏州大学应用技术学院",
    major: "软件工程",
    degree: "本科",
    time: {
      start: "2023-09",
      end: "2027-07",
    },
    description: ["学院工作室前端负责人，独立多个真实企业项目前端开发"],
  },
  skills: {
    mainSkills: [
      {
        name: "HTML/CSS",
        level: 70,
        gradient: "linear-gradient(90deg, #50fa7b 0%, #8be9fd 100%)",
      },
      {
        name: "JavaScript",
        level: 75,
        gradient: "linear-gradient(90deg, #8be9fd 0%, #bd93f9 100%)",
      },
      {
        name: "TypeScript",
        level: 20,
        gradient: "linear-gradient(90deg, #bd93f9 0%, #ff5555 100%)",
      },
      {
        name: "React",
        level: 30,
        gradient: "linear-gradient(90deg, #ff79c6 0%, #bd93f9 100%)",
      },
      {
        name: "Vue.js",
        level: 60,
        gradient: "linear-gradient(90deg, #ffb86c 0%, #50fa7b 100%)",
      },
    ],
    descriptions: [
      "前端基础: HTML5、CSS3、JavaScript(ES6+)、TypeScript、Flex/Grid响应式布局",
      "前端框架: Vue.js、React、Uniapp及其周边组件库、熟练v-charts等可视化工具(绘制可视化图表)",
      "中后台框架: 熟练使用Ant Design Pro、Vben Admin等构建后台管理系统",
      "Node: 了解Express等开发框架",
      "前端工具: 了解Webpack、了解vite构建工具、熟练使用ESLint等规则工具",
      "协同开发: 熟悉Git、具有多次协同开发经验、熟悉GitHub、Gitee、Coding等托管平台",
      "服务端: 熟悉使用Java/Mysql/Springboot、了解docker部署",
    ],
  },
  workExperiences: [
    {
      id: 1,
      company: "昆山悦云网络科技有限公司",
      position: "前端工程师",
      period: "2025.03 - 至今",
      description: [
        "负责相关项目的需求沟通及设计，梳理流程、绘制草图、流程图",
        "参与产品及项目的前端架构搭建、开发",
        "对产品进行相关的测试工作",
        "根据客户需求对项目进行持续的更新、维护",
      ],
      location: {
        address: "江苏省苏州市昆山市",
        coordinates: "120.845315,31.146251",
      },
    },
  ],
  projects: [
    {
      id: 1,
      name: "昆山高新区巡检系统",
      status: "进行中",
      description: "商铺安全隐患排查与可视化平台，支持5000+商户管理。",
      darkColor: "#7048e8",
      coverImage: "./safe_project.webp",
      link: "https://ksnd.nexinfo.cn/safety/user/login",
      details: {
        intro:
          "为昆山高新区部门开发全域商铺安全隐患排查平台，覆盖5000+商户管理，实现隐患上报、整改跟踪、数据可视化闭环。",
        tech: [
          "系统架构与核心开发：基于React + Ant Design Pro从0到1搭建项目，实现动态路由、权限管理、页面缓存及数据看板模块",
          "Mock数据：通过自定义mock数据，模拟后端接口格式，提升前端开发进度，实现独立开发/测试",
          "地图集成：接入高德地图API，实现点标记、自定义窗口显示详情数据，优化地图模块性能，接口请求频率降低30%",
          "数据可视化集成：在表单页面集成Echart可视化图表，点击图表分类即可执行查询，显著用户体验和查询效率",
          "组件化提取：封装多角色表单提交组件，通过自定义接收参数，提升页面通用性，实现组件独立",
        ],
        tags: [
          "React",
          "Ant Design Pro",
          "Echarts",
          "高德地图API",
          "Mock数据",
          "组件封装",
        ],
        period: "2025年3月 - 至今",
        role: "前端开发",
      },
    },
    {
      id: 2,
      name: "RTB - 简历到博客",
      status: "进行中",
      description: "在线编辑预览简历，根据简历自动生成博客",
      darkColor: "#6E10CC",
      coverImage: "",
      link: "https://cokoii.github.io/RTB/",
      details: {
        intro:
          "基于React与TypeScript开发的个人简历和技术博客结合的展示平台，采用现代前端技术栈实现响应式设计，支持项目展示、技能展示和工作经历等多维度内容展示，为个人提供专业形象的在线简历与作品集。",
        tech: [
          "技术选型：使用React 19 + TypeScript + Vite构建项目，实现高性能渲染与类型安全开发",
          "响应式设计：采用SCSS预处理器与Flex/Grid布局，实现全设备适配，优化移动端用户体验",
          "组件封装：基于Ant Design组件库进行二次封装，打造统一风格的UI界面与交互效果",
          "状态管理：使用React Context API管理全局状态，避免组件间的props层层传递",
          "路由配置：基于React Router实现单页应用路由管理，优化页面切换体验",
          "动画效果：结合CSS动画与React hooks实现平滑过渡效果，提升用户体验",
          "性能优化：使用组件懒加载、代码分割等技术优化首屏加载速度，提升性能表现",
        ],
        tags: [
          "React",
          "TypeScript",
          "Vite",
          "Ant Design",
          "SCSS",
          "响应式设计",
        ],
        period: "2025年5月",
        role: "全栈开发",
      },
    },
    {
      id: 3,
      name: "格屋客户订单系统",
      status: "已完成",
      description: "企业级数字化物料系统，多角色权限控制与流转记录可视化。",
      darkColor: "#5571ee",
      coverImage: "./gu_project.webp",
      link: "http://139.196.108.216/guplus",
      details: {
        intro:
          "面向企业内部人员和合作客户，提供数据存储、处理、可视化全流程管理的数字化平台，支持PC端与App协同办公，实现可视化权限管理、角色权限控制、数据流转日志审计等功能。",
        tech: [
          "系统架构与核心开发：基于Vue3 + Vben Admin + Ant Design Vue 从0到1搭建项目，主要实现动态路由、权限配置及数据看板模块",
          "组件化提效：表单分模块封装，复杂字段频组件化处理，支持 Excel 导入导出，数据处理效率提升65%",
          "大数据导入处理：采用懒加载、分页、Loading 等机制提升页面响应效率，减少30% 数据处理时间",
          "用户体验优化：自定义跳转页配置、标签页缓存等机制减少误操作，提高用户操作连贯性",
          "可视化布局：拖拽布局 + 拖动坐标组件，用户可自定义展示模块，实现页面区块化配置",
          "AI辅助功能：接入 Copilot、Claude3.7 等辅助开发工具，辅助代码优化、减少低效重复逻辑",
        ],
        tags: [
          "Vue3",
          "Vben Admin",
          "权限系统",
          "Excel导入导出",
          "AI辅助",
          "组件封装",
        ],
        period: "2024年11月 - 2025年4月",
        role: "前端开发",
      },
    },
    {
      id: 4,
      name: "VoidUI组件库",
      status: "进行中",
      description: "构建 Vue + TS 的现代组件库，提供统一UI设计与高复用组件",
      darkColor: "#4e8cff",
      coverImage: "",
      link: "https://cokoii.github.io/VoidUI",
      details: {
        intro:
          "开发 VoidUI 前端组件库，提供统一的 UI 设计规范和可复用组件，覆盖 Button、Icon、Table 等核心组件，实现开发标准化、提升开发者效率。",
        tech: [
          "系统架构与核心开发：基于 Vue 3 + TypeScript + Vite 搭建组件库架构，采用 Composition API 实现组件状态管理、主题切换、路由配置与文档展示模块",
          "组件规范与模块化设计：统一 UI 规范，封装 Button、Icon 等基础组件，采用模块化结构和 TypeScript 类型定义确保组件 API 规范性与独立按需引入",
          "文档系统构建：集成 Shiki 语法高亮与自定义 CodePreview 组件，支持代码预览、复制、多语言高亮，提升开发者使用体验与查阅效率",
          "构建与自动部署：使用 Vite 构建工具链优化打包性能，集成 GitHub Pages 和 CI/CD 实现自动化部署与文档发布",
          "开发体验优化：引入 Vue DevTools、ESLint、Prettier，建立代码规范检查机制，结合 Sass 实现主题定制化配置与样式组织",
        ],
        tags: ["组件库", "开发规范", "自动部署", "文档系统"],
        period: "2025-07 - 至今",
        role: "前端开发",
      },
    },
  ],
};

export default UserInfo;
